# Generated by Django 4.1.5 on 2023-01-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name')),
                ('photo', models.ImageField(upload_to='products', verbose_name='Photo')),
                ('description', models.TextField(verbose_name='Description')),
                ('ingridients', models.TextField(verbose_name='Ingridients')),
                ('customer', models.ManyToManyField(related_name='customer', to='customer.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
